version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pipeline-network

  api:
    build: .
    container_name: fastapi-server
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      MLFLOW_TRACKING_URI: file:/Users/Anna/ecommerce-data-pipeline/mlruns
      USE_BIGQUERY: ${USE_BIGQUERY}
      GCP_PROJECT: ${GCP_PROJECT}
      GOOGLE_CLOUD_PROJECT: ${GCP_PROJECT}
      GCS_BUCKET: ${GCS_BUCKET}
      GOOGLE_APPLICATION_CREDENTIALS: /root/.config/gcloud/application_default_credentials.json
    ports:
      - "8000:8000"
    volumes:
      - .:/Users/Anna/ecommerce-data-pipeline
      - ~/.config/gcloud:/root/.config/gcloud:ro
    working_dir: /Users/Anna/ecommerce-data-pipeline
    depends_on:
      - db
    networks:
      - pipeline-network

  mlflow:
    build: .
    container_name: mlflow-server
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri file:///Users/Anna/ecommerce-data-pipeline/mlruns --default-artifact-root file:///Users/Anna/ecommerce-data-pipeline/mlruns
    ports:
      - "5001:5000"
    volumes:
      - .:/Users/Anna/ecommerce-data-pipeline
    working_dir: /Users/Anna/ecommerce-data-pipeline
    networks:
      - pipeline-network

  dashboard:
    build: .
    container_name: streamlit-dashboard
    command: streamlit run streamlit_app.py --server.port 8501 --server.address 0.0.0.0
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      API_URL: http://api:8000
      USE_BIGQUERY: ${USE_BIGQUERY}
      GCP_PROJECT: ${GCP_PROJECT}
      GOOGLE_CLOUD_PROJECT: ${GCP_PROJECT}
      GCS_BUCKET: ${GCS_BUCKET}
      GOOGLE_APPLICATION_CREDENTIALS: /root/.config/gcloud/application_default_credentials.json
    ports:
      - "8501:8501"
    volumes:
      - .:/Users/Anna/ecommerce-data-pipeline
      - ~/.config/gcloud:/root/.config/gcloud:ro
    working_dir: /Users/Anna/ecommerce-data-pipeline
    depends_on:
      - api
    networks:
      - pipeline-network

volumes:
  postgres_data:

networks:
  pipeline-network:
    driver: bridge
