artifact_uri: file:///Users/Anna/ecommerce-data-pipeline/{Path('mlruns').resolve()}/958840658077389200/85c2fb94575f4ee894f0bfa85e5d8550/artifacts
end_time: 1773945784947
entry_point_name: ''
experiment_id: '958840658077389200'
lifecycle_stage: active
run_id: 85c2fb94575f4ee894f0bfa85e5d8550
run_name: kmeans_k4_default
source_name: ''
source_type: 4
source_version: ''
start_time: 1773945783278
status: 3
tags: []
user_id: Anna
