"""
Canonical File Paths & Directory Layout.
Maintained for backward compatibility; dynamically derived from central Pydantic Settings.
"""

from config.settings import get_settings

_settings = get_settings()

BASE_DIR = _settings.BASE_DIR
DATA_DIR = _settings.DATA_DIR
RAW_DIR = _settings.RAW_DIR
PROCESSED_DIR = _settings.PROCESSED_DIR
PREDICTIONS_DIR = _settings.PREDICTIONS_DIR
REPORTS_DIR = _settings.REPORTS_DIR
MODELS_DIR = _settings.MODELS_DIR
CONFIG_DIR = _settings.CONFIG_DIR

DIRECTORIES = [
    DATA_DIR,
    RAW_DIR,
    PREDICTIONS_DIR,
    PROCESSED_DIR,
    REPORTS_DIR,
    MODELS_DIR,
    CONFIG_DIR
]

ONLINE_RETAIL_XLSX = _settings.ONLINE_RETAIL_XLSX
ONLINE_RETAIL_CSV = _settings.ONLINE_RETAIL_CSV
CLEAN_RETAIL = _settings.CLEAN_RETAIL
FEATURE_RETAIL = _settings.FEATURE_RETAIL
RFM_CUSTOMERS = _settings.RFM_CUSTOMERS
TRAIN_CLUSTERS = _settings.TRAIN_CLUSTERS
CLUSTER_PROFILE = _settings.CLUSTER_PROFILE
CUSTOMER_CLUSTERS = _settings.CUSTOMER_CLUSTERS
CUSTOMER_CLUSTERS_V2 = _settings.CUSTOMER_CLUSTERS_V2
CUSTOMER_CLUSTERS_LABELED = _settings.CUSTOMER_CLUSTERS_LABELED
CUSTOMER_CLUSTERS_DB = _settings.CUSTOMER_CLUSTERS_DB
EXPERIMENT_CONFIG_PATH = _settings.EXPERIMENT_CONFIG_PATH
