artifact_uri: file:///Users/Anna/ecommerce-data-pipeline/{Path('mlruns').resolve()}/958840658077389200/66c7ebafa79c4a78b7e0d4d40da18441/artifacts
end_time: 1773951429359
entry_point_name: ''
experiment_id: '958840658077389200'
lifecycle_stage: active
run_id: 66c7ebafa79c4a78b7e0d4d40da18441
run_name: kmeans_k4_default
source_name: ''
source_type: 4
source_version: ''
start_time: 1773951427712
status: 3
tags: []
user_id: Anna
